services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    # volumes:
      # - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    command:
      - fastapi
      - run
      - "app/main.py"
      - --port
      - "80"
      - --reload
    volumes:
      - ./app:/code/app
    ports:
      - "8000:80"
    depends_on:
      - db

# volumes:
  # pgdata:
