services:
  fastapi:
    build: .
    command:
      - fastapi
      - run
      - "app/main.py"
      - --port
      - "80"
      - --reload
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
    ports:
      - "8000:80"
